openapi: 3.0.0
info:
  title: Social Media Configuration
  description: Adds, updates, and lists social media accounts
  version: 1.0.0
tags:
  - name: Account
    description: |
      Operations to manage maintenance of a social media account
  - name: Auth
    description: Operations to handle authN and authZ
  - name: Schedule
    description: Operations to manage scheduling posts

x-amazon-apigateway-request-validators:
  Validate All:
    validateRequestParameters: true
    validateRequestBody: true
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{ "message": "$context.error.validationErrorString" }'

x-amazon-apigateway-cors:
  allowOrigins:
    - '*'
  allowMethods:
    - GET
    - POST
    - PUT
  allowHeaders:
    - authorization
    - content-type
  maxAge: 3600

paths:
  /accounts:
    get:
      summary: List accounts
      description: Returns a page that lists accounts for a user
      tags:
        - Account
      responses:
        200:
          description: The request succeeded and the accounts are listed
          content:
            text/html:
              schema:
                type: string
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListAccountsFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /accounts/{accountId}:
    parameters:
      - $ref: '#/components/parameters/accountId'
    get:
      summary: Get account details
      description: Returns a form for account configuration
      tags:
        - Account
      responses:
        200:
          description: The request succeeded and the item is included in the response.
          content:
            text/html:
              schema:
                type: string
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AccountConfigView.Arn}/invocations
        httpMethod: POST
        type: aws_proxy
    put:
      summary: Update account information
      description: Replaces all details for an existing account with the data passed in the request body
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDetail'
        required: true
      responses:
        204:
          $ref: '#/components/responses/NoContentUpdate'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateAccountFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /accounts/{accountId}/messages:
    parameters:
      - $ref: '#/components/parameters/accountId'
    post:
      summary: Send a message
      description: Sends a message to the specified account
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  minLength: 1
                platform:
                  type: string
                  enum: [x, linkedIn, discord]
              required:
                - message
                - platform
      responses:
        201:
          description: The request succeeded and the message was sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        400:
          $ref: '#/components/responses/ClientError'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendTestPostFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /linkedin/login:
    post:
      summary: Authenticate integration with LinkedIn
      description: Go through 3-legged OAuth flow to authenticate with LinkedIn
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                  minLength: 1
              required:
                - accountId
      responses:
        200:
          description: The request succeeded and an auth url is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthenticateLinkedInFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /x/login:
    get:
      summary: Authenticate integration with X
      description: Go through 3-legged OAuth flow to authenticate with X
      parameters:
        - name: name
          in: query
          description: Name of the account
          required: false
          schema:
            type: string
      tags:
        - Auth
      responses:
        200:
          description: The request succeeded and an auth url is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginUrl:
                    type: string
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetXRedirectFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /confirmations/{referenceNumber}:
    parameters:
      - $ref: '#/components/parameters/referenceNumber'
      - $ref: '#/components/parameters/token'
    get:
      summary: Resumes scheduling posts
      description: For posts going through a verification flow, resumes the process after human validation
      tags:
        - Schedule
      responses:
        200:
          description: The request succeeded and an auth url is returned
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeSchedulingFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /confirmations/{referenceNumber}/messages:
    parameters:
      - $ref: '#/components/parameters/referenceNumber'
      - $ref: '#/components/parameters/token'
    get:
      summary: Review messages
      description: Verify message content before sending
      tags:
        - Schedule
      responses:
        200:
          description: The request succeeded and the item is included in the response.
          content:
            text/html:
              schema:
                type: string
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReviewMessagesFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /confirmations/{referenceNumber}/messages/{messageId}:
    parameters:
      - $ref: '#/components/parameters/referenceNumber'
      - $ref: '#/components/parameters/token'
      - name: messageId
        in: path
        description: Identifier for a message
        required: true
        example: kdsfgjlksdfg-0
        schema:
          type: string
    put:
      summary: Update message
      description: Update information about a message
      tags:
        - Schedule
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  minLength: 1
              required:
                - message
      responses:
        204:
          $ref: '#/components/responses/NoContentUpdate'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateDeleteMessageFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: Delete a message
      description: Deletes a proposed message to be sent
      tags:
        - Messages
      responses:
        204:
          $ref: '#/components/responses/NoContentUpdate'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: Validate All
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateDeleteMessageFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

components:
  parameters:
    accountId:
      name: accountId
      in: path
      description: Identifier for an account
      required: true
      example: 09sl3415098gplmn
      schema:
        type: string

    referenceNumber:
      name: referenceNumber
      in: path
      description: Identifier for a scheduling batch
      required: true
      example: argkasdfguaksdfna
      schema:
        type: string

    token:
      name: token
      in: query
      description: Temporary auth token
      required: true
      example: kfrkjkjbnmfk
      schema:
        type: string

  schemas:
    AccountMetadata:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
        id:
          type: string

    AccountDetail:
      type: object
      properties:
        x:
          type: object
          properties:
            apiKey:
              type: string
            apiKeySecret:
              type: string
            accessToken:
              type: string
            accessTokenSecret:
              type: string
            bearerToken:
              type: string
            removeCredentials:
              type: boolean
        linkedIn:
          type: object
          properties:
            type:
              type: string
              enum: [personal, organization]
            organizationId:
              type: string
            removeCredentials:
              type: boolean
        discord:
          type: object
          properties:
            channel:
              type: string

  responses:
    Created: #201
      description: The request succeeded and created a new account
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
            required:
              - id
    NoContentUpdate: #204
      description: The request succeeded and updated an existing item
    ClientError: #400
      description: The request was in an invalid format
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Could not perform operation with provided data
            required:
              - message
    NotFound: #404
      description: The requested item was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Could not find an account with the specified id.
            required:
              - message
    Conflict: #409
      description: The requested item was not in the proper state
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: The provided platform is not configured
            required:
              - message
    InternalServerError: #500
      description: The server encountered an unexpected condition which prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: An error occurred saving the item.
            required:
              - message
